[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "nodejs_18",
  "npm-9_x"
]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "php artisan config:clear",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "npm ci",
  "npm run build"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
