services:
  - type: web
    name: coro-web
    env: php
    region: oregon
    plan: free
    branch: main
    buildCommand: "composer install && npm install && npm run build"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: supabase
      - key: SUPABASE_HOST
        value: aws-0-us-west-1.pooler.supabase.com
      - key: SUPABASE_PORT
        value: 6543
      - key: SUPABASE_DB
        value: postgres
      - key: SUPABASE_USER
        value: postgres.duauzyjxgpvyhqcsjwbm
      - key: SUPABASE_PASSWORD
        value: 64751713
